---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: example-app #TODO: Change to your app name
    newName: ghcr.io/fellesdatakatalog/hackathon-autoharvest/example-app #TODO: Change to your app name
    newTag: $(GIT_COMMIT_SHA)
