name: Validate SHACL with Pytest

on:
  push:
    paths:
      - "examples/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
          poetry install dependencies/maplib-0.12.10-cp311-cp311-manylinux_2_34_x86_64.whl
        continue-on-error: true
      - name: Run tests
        run: |
          poetry run pytest
